# Generated by Django 5.1.6 on 2025-03-24 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_attendance_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='AproveUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aprove_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'طلبات التنشيط',
            },
        ),
    ]
